## NetworkManager.gd
## Owns all ENet peer lifecycle — solo, LAN (2-player), and same-machine play.
extends Node


# =========================================================
# CONSTANTS
# =========================================================

## ENet game port. Clients connect here for gameplay traffic.
const PORT:               int   = 7000

## Fallback IP used when join_game() is called with no argument.
const DEFAULT_SERVER_IP:  String = "127.0.0.1"

## Maximum peers excluding the host (host + 1 = 2 players).
const MAX_PEERS:          int   = 1

## Length of the auto-generated session key.
const KEY_LENGTH:         int   = 6

## UDP port used for LAN discovery broadcasts.
const DISCOVERY_PORT:     int   = 7778

## How often the host re-broadcasts the key, in seconds.
const BROADCAST_INTERVAL: float = 1.0

## How long the client listens for a matching broadcast before giving up.
const DISCOVERY_TIMEOUT:  float = 5.0

## Magic prefix to avoid collisions with unrelated UDP traffic.
const PACKET_PREFIX:      String = "FF_KEY:"

## Seconds in the pre-game countdown.
const COUNTDOWN_DURATION: int = 3


# =========================================================
# STATE
# =========================================================

## Player registry — same structure your UI already reads.
## { peer_id: { "id": int, "name": String } }
var players: Dictionary = {}

## The session key generated by the host each match. Empty when not hosting.
var session_key: String = ""

## UDP socket used by the host to broadcast the session key.
var _broadcast_socket: PacketPeerUDP = null

## Timer node driving the broadcast interval loop.
var _broadcast_timer: Timer = null


# =========================================================
# SIGNALS  (all original signals preserved)
# =========================================================

signal player_list_updated
signal match_started

## Emitted when key discovery times out with no matching host found.
signal discovery_failed

## Emitted on all peers each countdown tick.
signal countdown_tick(seconds_remaining: int)


# =========================================================
# LIFECYCLE
# =========================================================

func _ready() -> void:
	multiplayer.peer_connected.connect(_on_peer_connected)
	multiplayer.peer_disconnected.connect(_on_peer_disconnected)
	multiplayer.connected_to_server.connect(_on_connected_to_server)
	multiplayer.connection_failed.connect(_on_connection_failed)


# =========================================================
# PUBLIC API
# =========================================================

## Generates a session key, starts an ENet server (max 1 client = 2 players),
## and begins UDP broadcast so a LAN client can discover us by key.
func host_game() -> void:
	leave_game()  # ensure clean state

	var peer := ENetMultiplayerPeer.new()
	var err  := peer.create_server(PORT, MAX_PEERS)
	if err != OK:
		printerr("NetworkManager: Failed to host on port %d — %s" % [PORT, error_string(err)])
		return

	multiplayer.multiplayer_peer = peer

	# Host is always peer ID 1.
	players[1] = {"id": 1, "name": "Player (Host)"}
	player_list_updated.emit()

	session_key = _generate_key()
	print("NetworkManager: Hosting. Session key = %s" % session_key)
	_start_udp_broadcast(session_key)


## Discovers the host on LAN by matching [key] via UDP, then connects via ENet.
## Falls back to direct IP join when [key] is empty (same-machine / manual IP).
## Emits discovery_failed if no host is found within DISCOVERY_TIMEOUT seconds.
func join_game(ip: String = "", key: String = "") -> void:
	leave_game()  # ensure clean state

	# --- LAN key discovery path ---
	if not key.is_empty():
		print("NetworkManager: Searching for host with key '%s'..." % key)
		var found_ip: String = await _discover_host_by_key(key)
		if found_ip.is_empty():
			push_warning("NetworkManager: Discovery timed out for key '%s'." % key)
			discovery_failed.emit()
			return
		ip = found_ip

	# --- Direct / fallback IP path ---
	if ip.is_empty():
		ip = DEFAULT_SERVER_IP

	print("NetworkManager: Connecting to host at %s..." % ip)
	var peer := ENetMultiplayerPeer.new()
	var err  := peer.create_client(ip, PORT)
	if err != OK:
		printerr("NetworkManager: Failed to connect to %s:%d — %s" % [ip, PORT, error_string(err)])
		return

	multiplayer.multiplayer_peer = peer


## Starts a solo game, bypassing all multiplayer infrastructure entirely.
## Loads World.tscn (or any [scene_path] you pass) immediately.
func start_single_player(scene_path: String = "res://scenes/match/match.tscn",
		player_name: String = "Player") -> void:
	leave_game()

	var offline_peer := OfflineMultiplayerPeer.new()
	multiplayer.multiplayer_peer = offline_peer

	players[1] = {"id": 1, "name": player_name}
	player_list_updated.emit()

	print("NetworkManager: Starting single-player.")
	# Re-use the existing match_started flow so UI reacts identically.
	_hide_menus.rpc()
	get_tree().change_scene_to_file(scene_path)


## Called by the host UI's Start button.
## Stops broadcast, runs a countdown on all peers, then loads the match scene.
func start_match() -> void:
	if not multiplayer.is_server():
		push_warning("NetworkManager: start_match() called on a non-server — ignoring.")
		return

	_stop_udp_broadcast()
	print("NetworkManager: Starting match — broadcasting countdown.")
	_run_countdown.rpc()


## Stops broadcasting, disconnects ENet, and resets all session state.
func leave_game() -> void:
	_stop_udp_broadcast()
	if multiplayer.multiplayer_peer:
		multiplayer.multiplayer_peer.close()
	multiplayer.multiplayer_peer = null
	players.clear()
	session_key = ""
	print("NetworkManager: Disconnected and session reset.")


# =========================================================
# SCENE TRANSITION RPC
# =========================================================

## Runs a countdown on every peer, then loads the match scene.
## Server-authoritative; executes locally on the server too via call_local.
@rpc("authority", "call_local", "reliable")
func _run_countdown() -> void:
	for i in range(COUNTDOWN_DURATION, 0, -1):
		countdown_tick.emit(i)
		await get_tree().create_timer(1.0).timeout
	# Load the match — adjust path to match your project.
	var match_scene: Node = load("res://scenes/match/match.tscn").instantiate()
	get_tree().root.get_node("Main/LevelContainer").add_child(match_scene)
	_hide_menus.rpc()


@rpc("call_local", "reliable")
func _hide_menus() -> void:
	match_started.emit()


# =========================================================
# PLAYER REGISTRY RPCs  (unchanged from original)
# =========================================================

@rpc("any_peer", "call_remote", "reliable")
func _register_player(id: int, player_name: String) -> void:
	if multiplayer.is_server():
		print("NetworkManager: Registering '%s' (ID %d)" % [player_name, id])
		players[id] = {"id": id, "name": player_name}
		player_list_updated.emit()
		_send_full_player_list.rpc(players)


@rpc("authority", "call_remote", "reliable")
func _send_full_player_list(updated_players: Dictionary) -> void:
	print("NetworkManager: Player list updated from server.")
	players = updated_players
	player_list_updated.emit()


# =========================================================
# UDP BROADCAST  (host side)
# =========================================================

func _start_udp_broadcast(key: String) -> void:
	_broadcast_socket = PacketPeerUDP.new()
	_broadcast_socket.set_broadcast_enabled(true)

	var err := _broadcast_socket.bind(0)
	if err != OK:
		push_error("NetworkManager: Failed to bind broadcast socket — %s" % error_string(err))
		return

	_broadcast_timer = Timer.new()
	_broadcast_timer.wait_time = BROADCAST_INTERVAL
	_broadcast_timer.autostart = true
	_broadcast_timer.one_shot  = false
	_broadcast_timer.timeout.connect(_send_broadcast.bind(key))
	add_child(_broadcast_timer)

	_send_broadcast(key)
	print("NetworkManager: UDP broadcast started for key '%s'." % key)


func _send_broadcast(key: String) -> void:
	if _broadcast_socket == null:
		return
	var message := (PACKET_PREFIX + key).to_utf8_buffer()
	var err     := _broadcast_socket.set_dest_address("255.255.255.255", DISCOVERY_PORT)
	if err != OK:
		push_error("NetworkManager: Broadcast destination error — %s" % error_string(err))
		return
	_broadcast_socket.put_packet(message)


func _stop_udp_broadcast() -> void:
	if _broadcast_timer:
		_broadcast_timer.stop()
		_broadcast_timer.queue_free()
		_broadcast_timer = null
	if _broadcast_socket:
		_broadcast_socket.close()
		_broadcast_socket = null


# =========================================================
# UDP DISCOVERY  (client side)
# =========================================================

## Listens on DISCOVERY_PORT for a broadcast packet matching [key].
## Returns the sender IP on success, or "" on timeout. Must be awaited.
func _discover_host_by_key(key: String) -> String:
	var listener := PacketPeerUDP.new()
	var err      := listener.bind(DISCOVERY_PORT)
	if err != OK:
		push_error("NetworkManager: Failed to bind discovery listener — %s" % error_string(err))
		listener.close()
		return ""

	var expected := PACKET_PREFIX + key
	var elapsed: float = 0.0

	while elapsed < DISCOVERY_TIMEOUT:
		await get_tree().process_frame
		elapsed += get_process_delta_time()

		while listener.get_available_packet_count() > 0:
			var packet  := listener.get_packet()
			var message := packet.get_string_from_utf8()
			var sender  := listener.get_packet_ip()
			if message == expected:
				print("NetworkManager: Matched key '%s' from %s." % [key, sender])
				listener.close()
				return sender

	listener.close()
	return ""


# =========================================================
# PRIVATE HELPERS
# =========================================================

func _generate_key() -> String:
	const CHARS := "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	var key     := ""
	for i in KEY_LENGTH:
		key += CHARS[randi() % CHARS.length()]
	return key


# =========================================================
# MULTIPLAYER SIGNAL HANDLERS
# =========================================================

func _on_peer_connected(id: int) -> void:
	print("NetworkManager: Peer connected — ID %d." % id)


func _on_peer_disconnected(id: int) -> void:
	print("NetworkManager: Peer disconnected — ID %d." % id)
	if multiplayer.is_server():
		players.erase(id)
		player_list_updated.emit()
		_send_full_player_list.rpc(players)


func _on_connected_to_server() -> void:
	print("NetworkManager: Connected. My peer ID = %d." % multiplayer.get_unique_id())
	var my_id := multiplayer.get_unique_id()
	_register_player.rpc_id(1, my_id, "Player " + str(my_id))


func _on_connection_failed() -> void:
	printerr("NetworkManager: Connection failed.")
	multiplayer.multiplayer_peer = null
